name: linux-nightly-install

on:
  pull_request:
    paths:
      - .github/issue-templates/linux-nightly-uninstallable.md
      - .github/workflows/linux-nightly-install.yml

  schedule:
    - cron: "40 4 * * *"

jobs:
  check:
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
      max-parallel: 1

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup development environment
        uses: ./.github/actions/setup-dev-env
        with:
          python-version: ${{ matrix.python-version }}

      - name:
          Try installing Linux nightly binaries exclusively from PyTorch wheels indices
        run:
          python -m pip install --pre torch torchvision torchaudio
          --index-url=https://download.pytorch.org/whl/nightly/cpu

      - if: failure()
        name: Publish information from template
        uses: ./.github/actions/publish-from-template
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ID: ${{ github.run_id }}
          VERSION: ${{ steps.latest.outputs.version }}
        with:
          filename: .github/issue-templates/linux-nightly-uninstallable.md
